import Day1 from '../pages/Days/Day-1';
import Day2 from '../pages/Days/Day-2';

// export const homeRoute = [{ path: '/', component }];

export const projectRoutes = [
    { path: '/day-1/expanding-cards', component: Day1, name: 'Expanding Cards', day: 'Day 1' },
    { path: '/day-2', component: Day2, name: 'Name', day: 'Day 2' },
    { path: '/day-3', component: Day2, name: 'Name', day: 'Day 3' },
    { path: '/day-4', component: Day2, name: 'Name', day: 'Day 4' },
    { path: '/day-5', component: Day2, name: 'Name', day: 'Day 5' },
    { path: '/day-6', component: Day2, name: 'Name', day: 'Day 6' },
    { path: '/day-7', component: Day2, name: 'Name', day: 'Day 7' },
    { path: '/day-8', component: Day2, name: 'Name', day: 'Day 8' },
    { path: '/day-9', component: Day2, name: 'Name', day: 'Day 9' },
    { path: '/day-10', component: Day2, name: 'Name', day: 'Day 10' },
    { path: '/day-1/expanding-cards', component: Day1, name: 'Expanding Cards', day: 'Day 11' },
    { path: '/day-2', component: Day2, name: 'Name', day: 'Day 12' },
    { path: '/day-3', component: Day2, name: 'Name', day: 'Day 13' },
    { path: '/day-4', component: Day2, name: 'Name', day: 'Day 14' },
    { path: '/day-5', component: Day2, name: 'Name', day: 'Day 15' },
    { path: '/day-6', component: Day2, name: 'Name', day: 'Day 16' },
    { path: '/day-7', component: Day2, name: 'Name', day: 'Day 17' },
    { path: '/day-8', component: Day2, name: 'Name', day: 'Day 18' },
    { path: '/day-9', component: Day2, name: 'Name', day: 'Day 19' },
    { path: '/day-10', component: Day2, name: 'Name', day: 'Day 20' },
    { path: '/day-1/expanding-cards', component: Day1, name: 'Expanding Cards', day: 'Day 21' },
    { path: '/day-2', component: Day2, name: 'Name', day: 'Day 22' },
    { path: '/day-3', component: Day2, name: 'Name', day: 'Day 23' },
    { path: '/day-4', component: Day2, name: 'Name', day: 'Day 24' },
    { path: '/day-5', component: Day2, name: 'Name', day: 'Day 25' },
    { path: '/day-6', component: Day2, name: 'Name', day: 'Day 26' },
    { path: '/day-7', component: Day2, name: 'Name', day: 'Day 27' },
    { path: '/day-8', component: Day2, name: 'Name', day: 'Day 28' },
    { path: '/day-9', component: Day2, name: 'Name', day: 'Day 29' },
    { path: '/day-10', component: Day2, name: 'Name', day: 'Day 30' },
    { path: '/day-1/expanding-cards', component: Day1, name: 'Expanding Cards', day: 'Day 31' },
    { path: '/day-2', component: Day2, name: 'Name', day: 'Day 32' },
    { path: '/day-3', component: Day2, name: 'Name', day: 'Day 33' },
    { path: '/day-4', component: Day2, name: 'Name', day: 'Day 34' },
    { path: '/day-5', component: Day2, name: 'Name', day: 'Day 35' },
    { path: '/day-6', component: Day2, name: 'Name', day: 'Day 36' },
    { path: '/day-7', component: Day2, name: 'Name', day: 'Day 37' },
    { path: '/day-8', component: Day2, name: 'Name', day: 'Day 38' },
    { path: '/day-9', component: Day2, name: 'Name', day: 'Day 39' },
    { path: '/day-10', component: Day2, name: 'Name', day: 'Day 40' },
    { path: '/day-1/expanding-cards', component: Day1, name: 'Expanding Cards', day: 'Day 41' },
    { path: '/day-2', component: Day2, name: 'Name', day: 'Day 42' },
    { path: '/day-3', component: Day2, name: 'Name', day: 'Day 43' },
    { path: '/day-4', component: Day2, name: 'Name', day: 'Day 44' },
    { path: '/day-5', component: Day2, name: 'Name', day: 'Day 45' },
    { path: '/day-6', component: Day2, name: 'Name', day: 'Day 46' },
    { path: '/day-7', component: Day2, name: 'Name', day: 'Day 47' },
    { path: '/day-8', component: Day2, name: 'Name', day: 'Day 48' },
    { path: '/day-9', component: Day2, name: 'Name', day: 'Day 49' },
    { path: '/day-10', component: Day2, name: 'Name', day: 'Day 50' },
];
