import * as Days from '../pages/Days'

export const projectRoutes = [
    { path: '/day-1-expanding-cards', component: Days.Day1, name: 'Expanding Cards', day: 'Day 1' },
    { path: '/day-2-progress-steps', component: Days.Day2, name: 'Progress Steps', day: 'Day 2' },
    {
        path: '/day-3-rotating-navigation-animation',
        component: Days.Day3,
        name: 'Rotating Navigation Animation',
        day: 'Day 3',
    },
    { path: '/day-4-hidden-search', component: Days.Day4, name: 'Hidden Search', day: 'Day 4' },
    { path: '/day-5-blurring-loading', component: Days.Day5, name: 'Blurring Loading', day: 'Day 5' },
    { path: '/day-6-scroll-animation', component: Days.Day6, name: 'Scroll Animation', day: 'Day 6' },
    { path: '/day-7-split-landing-page', component: Days.Day7, name: 'Split Landing Page', day: 'Day 7' },
    { path: '/day-8-form-wave', component: Days.Day8, name: 'Form Wave', day: 'Day 8' },
    { path: '/day-9-sound-board', component: Days.Day9, name: 'Sound Board', day: 'Day 9' },
    { path: '/day-10-dad-jokes', component: Days.Day10, name: 'Dad Jokes', day: 'Day 10' },
    { path: '/day-11-event-keycodes', component: Days.Day11, name: 'Event KeyCodes', day: 'Day 11' },
    { path: '/day-12-faq-collapse', component: Days.Day12, name: 'FAQ Collapse', day: 'Day 12' },
    { path: '/day-13', component: Days.Day2, name: 'Name', day: 'Day 13' },
    { path: '/day-14', component: Days.Day2, name: 'Name', day: 'Day 14' },
    { path: '/day-15', component: Days.Day2, name: 'Name', day: 'Day 15' },
    { path: '/day-16', component: Days.Day2, name: 'Name', day: 'Day 16' },
    { path: '/day-17', component: Days.Day2, name: 'Name', day: 'Day 17' },
    { path: '/day-18', component: Days.Day2, name: 'Name', day: 'Day 18' },
    { path: '/day-19', component: Days.Day2, name: 'Name', day: 'Day 19' },
    { path: '/day-20', component: Days.Day2, name: 'Name', day: 'Day 20' },
    { path: '/day-21', component: Days.Day2, name: 'Expanding Cards', day: 'Day 21' },
    { path: '/day-22', component: Days.Day2, name: 'Name', day: 'Day 22' },
    { path: '/day-23', component: Days.Day2, name: 'Name', day: 'Day 23' },
    { path: '/day-24', component: Days.Day2, name: 'Name', day: 'Day 24' },
    { path: '/day-25', component: Days.Day2, name: 'Name', day: 'Day 25' },
    { path: '/day-26', component: Days.Day2, name: 'Name', day: 'Day 26' },
    { path: '/day-27', component: Days.Day2, name: 'Name', day: 'Day 27' },
    { path: '/day-28', component: Days.Day2, name: 'Name', day: 'Day 28' },
    { path: '/day-29', component: Days.Day2, name: 'Name', day: 'Day 29' },
    { path: '/day-30', component: Days.Day2, name: 'Name', day: 'Day 30' },
    { path: '/day-31', component: Days.Day2, name: 'Expanding Cards', day: 'Day 31' },
    { path: '/day-32', component: Days.Day2, name: 'Name', day: 'Day 32' },
    { path: '/day-33', component: Days.Day2, name: 'Name', day: 'Day 33' },
    { path: '/day-34', component: Days.Day2, name: 'Name', day: 'Day 34' },
    { path: '/day-35', component: Days.Day2, name: 'Name', day: 'Day 35' },
    { path: '/day-36', component: Days.Day2, name: 'Name', day: 'Day 36' },
    { path: '/day-37', component: Days.Day2, name: 'Name', day: 'Day 37' },
    { path: '/day-38', component: Days.Day2, name: 'Name', day: 'Day 38' },
    { path: '/day-39', component: Days.Day2, name: 'Name', day: 'Day 39' },
    { path: '/day-40', component: Days.Day2, name: 'Name', day: 'Day 40' },
    { path: '/day-41', component: Days.Day2, name: 'Expanding Cards', day: 'Day 41' },
    { path: '/day-42', component: Days.Day2, name: 'Name', day: 'Day 42' },
    { path: '/day-43', component: Days.Day2, name: 'Name', day: 'Day 43' },
    { path: '/day-44', component: Days.Day2, name: 'Name', day: 'Day 44' },
    { path: '/day-45', component: Days.Day2, name: 'Name', day: 'Day 45' },
    { path: '/day-46', component: Days.Day2, name: 'Name', day: 'Day 46' },
    { path: '/day-47', component: Days.Day2, name: 'Name', day: 'Day 47' },
    { path: '/day-48', component: Days.Day2, name: 'Name', day: 'Day 48' },
    { path: '/day-49', component: Days.Day2, name: 'Name', day: 'Day 49' },
    { path: '/day-50', component: Days.Day2, name: 'Name', day: 'Day 50' },
]
